### ISSUE TITLE
Share inventories between players rather than creating new ones

### ISSUE THREAD

**Issue by LooFifteen** [ZakShearman/mc-tower-defence#76]
Sharing inventories between players for the upgrade UI, mob spawning UI, etc. will make it easier to synchronize the inventories if multiple players have them open at the same time. This will work as there are no moving items in any of the inventories. Any action in UI will change a single inventory and will be reflected amongst all players will little-to-no effort.

**Comment by ZakShearman** [comment]
But there are moving items in the inventories or items that are unique to each player?

Upgrade UI:
- Is specific to the mobs you have unlocked, upgraded, etc..

Mob Spawning UI:
- Is specific to the mobs you have unlocked, upgraded, etc..
- Shows a live updating item of your queue

I'm not aware of a single GUI in the game **apart from tower GUIs** that can be common between users. Even tower UIs will likely need to be user specific in the future if there are upgrade paths (i.e to prevent griefing by only allowing the user that placed to tower to choose the path).

**Comment by LooFifteen** [comment]
I see. I didn't realise that unlocks are user-specific.
